spring.application.name=CampusMart

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/campusmart?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata
spring.datasource.username=root
spring.datasource.password=Mysql@5417

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# JSON
spring.jackson.serialization.fail-on-empty-beans=false